### ISSUE TITLE
Consider pre-populating more of the obs_status.yml file

### ISSUE THREAD

**Issue by taldcroft** [sot/agasc#116]
Most (probably 90% or more) of the dispositions will be `Never acquired. Set mag to MAXMAG`. Finding the MAXMAG manually is a bit of a pain and error prone. (In fact I almost made a mistake in doing it this week because I was fooled by a color=1.5 star that I assumed was the bad one).

Since it is easier to delete or slightly modify YAML content then it is to compose it by hand, I propose that the auto-generated obs status file look like below. The comments
```
obs:
  - mp_starcat_time: 2021:154:16:23:25.445
    obsid: 46314
    status: 1
    agasc_id: [813964024]
    comments: Never acquired. Set mag to MAXMAG  
    ¡¡ CONFIRM or change !!

bad:
  813964024: 9  
  ¡¡ CONFIRM or change !!

mags:
  - agasc_id: 813964024
    mag_aca: 9.812
    mag_aca_err: 0.1
    ¡¡ CONFIRM or change !!
```
In essence make the whole thing correct for the most common disposition and then allow the reviewer to edit or accept.

The slightly funky `¡¡ CONFIRM or change !!` is negotiable, but what this does is makes the file be invalid YAML so it cannot be accidentally ingested without the reviewer specifically accepting each entry.
